services:
  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

#  fortune-app:
#    build: .
#    container_name: fortune-app
#    restart: unless-stopped
#    ports:
#      - "8080:8080"
#    environment:
#      MYSQL_HOST: mysql-container
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/${MYSQL_DATABASE}
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      SPRING_REDIS_HOST: redis-container
#      SPRING_REDIS_PORT: 6379
#    depends_on:
#      - mysql-container
#      - redis-container

volumes:
  mysql_data:
  redis_data: